# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvstore.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'kvstore.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rkvstore.proto\x12\x07kvstore\"&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x12\n\x03Key\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1b\n\x06Prefix\x12\x11\n\tprefixKey\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"+\n\x0bGetResponse\x12\r\n\x05value\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"#\n\x11GetPrefixResponse\x12\x0e\n\x06values\x18\x01 \x03(\t\"Q\n\x0cStatResponse\x12\x12\n\ntotal_sets\x18\x01 \x01(\x05\x12\x12\n\ntotal_gets\x18\x02 \x01(\x05\x12\x19\n\x11total_getprefixes\x18\x03 \x01(\x05\x32\xc7\x01\n\x07KVStore\x12(\n\x03set\x12\x11.kvstore.KeyValue\x1a\x0e.kvstore.Empty\x12)\n\x03get\x12\x0c.kvstore.Key\x1a\x14.kvstore.GetResponse\x12\x38\n\tgetPrefix\x12\x0f.kvstore.Prefix\x1a\x1a.kvstore.GetPrefixResponse\x12-\n\x04stat\x12\x0e.kvstore.Empty\x1a\x15.kvstore.StatResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kvstore_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KEYVALUE']._serialized_start=26
  _globals['_KEYVALUE']._serialized_end=64
  _globals['_KEY']._serialized_start=66
  _globals['_KEY']._serialized_end=84
  _globals['_PREFIX']._serialized_start=86
  _globals['_PREFIX']._serialized_end=113
  _globals['_EMPTY']._serialized_start=115
  _globals['_EMPTY']._serialized_end=122
  _globals['_GETRESPONSE']._serialized_start=124
  _globals['_GETRESPONSE']._serialized_end=167
  _globals['_GETPREFIXRESPONSE']._serialized_start=169
  _globals['_GETPREFIXRESPONSE']._serialized_end=204
  _globals['_STATRESPONSE']._serialized_start=206
  _globals['_STATRESPONSE']._serialized_end=287
  _globals['_KVSTORE']._serialized_start=290
  _globals['_KVSTORE']._serialized_end=489
# @@protoc_insertion_point(module_scope)
